add shebang to all files, check if functions exist and if not, import them

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,4 +1,10 @@
+#!/bin/bash
+
 # Functions from https://github.com/thoughtbot/laptop/
+
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
 
 fancy_echo() {
   local fmt="$1"; shift
